sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8

env:
  global:
    - DOCKER_EMAIL=tbd
    - DOCKER_USER=tbd
    - DOCKER_PASS=tbd
    - COMMIT=${TRAVIS_COMMIT::8}

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x gradlew

script: ./gradlew build

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=lreimer/cloud-native-zuul
  - export TAG=`if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker tag $REPO:$COMMIT $REPO:latest
  - docker push $REPO
